export const puppyList = [
    {
      id: 1,
      name: "Sir Waggington",
      email: "sir-wag@email.com",
      imageUrl: "https://i.etsystatic.com/25132352/r/il/d4141d/2806283271/il_fullxfull.2806283271_sxpt.jpg",
      isCute: true,
      age: 5,
      ownerId: 1,
      tricks: [
        { id: 2, title: "Lay Down" },
        { id: 3, title: "Jump through flaming hoop" },
      ],
    },
    {
      id: 2,
      name: "Fiona Penny Pickles",
      email: "pick-your-pennies@email.com",
      imageUrl: "https://ae01.alicdn.com/kf/HTB1CczTiByWBuNkSmFPq6xguVXal/Summer-Dog-Dress-Pet-Dog-Clothes-for-Small-Dog-Wedding-Dress-Skirt-Puppy-Clothing-Spring-Fashion.jpg",
      isCute: true,
      age: 6,
      ownerId: 1,
      tricks: [],
    },
    {
      id: 3,
      name: "Professor Wagglesworth",
      email: "waggie@email.com",
      imageUrl: "https://th.bing.com/th/id/R.02568089cfa85eca4a52748a3d563f77?rik=SCewT7sPJHykbw&riu=http%3a%2f%2fi.huffpost.com%2fgen%2f3781196%2fimages%2fo-DOG-SCIENTIST-facebook.jpg&ehk=c1rud1F6on7bP4uAU1oabAaRrWrjcv1efPa6v7vK0CQ%3d&risl=&pid=ImgRaw&r=0",
      isCute: true,
      age: 6,
      ownerId: 2,
      tricks: [{ id: 1, title: "Sit" }],
    },
    {
      id: 4,
      name: "Sergeant Barkowitz",
      email: "the-sarge@email.com",
      imageUrl: "https://wallup.net/wp-content/uploads/2014/10/animal/Dog_Army_Awesome.jpg",
      isCute: true,
      age: 4,
      ownerId: 2,
      tricks: [{ id: 2, title: "Lay Down" }],
    },
    {
      id: 5,
      name: "Captain Sniffer",
      email: "capn-sniff@email.com",
      imageUrl: "https://th.bing.com/th/id/OIP.fKVKQ19pnzqIN4QvPh5WlgHaJd?pid=ImgDet&rs=1",
      isCute: true,
      age: 7,
      ownerId: 3,
      tricks: [],
    },
    {
      id: 6,
      name: "Miss Furbulous",
      email: "miss-furby@email.com",
      imageUrl: "https://www.elle.be/nl/wp-content/uploads/2018/01/fashion_dog_hond_mode_modeweek_fashion_week_frint_row_doggo_puppy_cute_6.jpg",
      isCute: true,
      age: 1,
      ownerId: 3,
      tricks: [],
    },
    {
      id: 7,
      name: "Alfred von Wigglebottom",
      email: "alfie@email.com",
      imageUrl: "https://i.pinimg.com/736x/4c/5f/f4/4c5ff49622938920102abdca806f1277--dog-tuxedo-groom-tuxedo.jpg",
      isCute: true,
      age: 2,
      ownerId: 3,
      tricks: [],
    },
  ];